### ISSUE TITLE
Add transparent as an overlay option

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#637]
**Is your feature request related to a problem? Please describe.**
Rather than needing to specify a chroma key most streaming software (OBS and XSplit anyway) will honor the alpha channel of a browser source.  It would be nice to add this as an option in the list of overlay colors.

**Describe the solution you'd like**
In addition to Green and Magenta add Transparent.

**Describe alternatives you've considered**
It is possible to do this currently in OBS studio by injecting some custom CSS.  It should be trivial to add the same CSS to the UI to do this without requiring any thing of the user.  Here is the minimum CSS required to make this work (note, important is required to override the UI, but if this is done in the DOM important should not be required):

```css
body { 
  background-color: rgba(0, 0, 0, 0) !important;
}
#displayRoot {
  background-color: rgba(0, 0, 0, 0) !important;
}
.chroma {
  background-color: rgba(0, 0, 0, 0) !important;
}
```

**Additional context**

**Comment by jvens** [comment]
Just noticed, it does require one more CSS rule to keep the black background for the randomization screen:
```css
.oneThirdContainer {
  background-color: black;
}
```
